name: MyAIGuide
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - scipy
  - pandas
  - dask
  - ipython
  - tqdm
  - click
  - matplotlib
  - seaborn
  - altair
  - statsmodels
  - scikit-learn
  - xlsxwriter
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - optuna
     - python-tcxparser
     - gpxpy
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - coverage
  - PyScaffold
  - requests
  - gpxpy
  - xlrd